# This file was generated by GoReleaser. DO NOT EDIT.
cask "ss" do
  name "ss"
  desc "All-in-one Go development toolkit with code generation and runtime utilities"
  homepage "https://github.com/ssgohq/ssgo"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ss"

  on_macos do
    on_intel do
      url "https://github.com/ssgohq/ssgo/releases/download/v#{version}/ss_Darwin_x86_64.tar.gz",
        verified: "github.com/ssgohq/ssgo"
      sha256 "1dc2a6e3514d3eba502560416339e0699733bf311fe774de477344e4f9544960"
    end
    on_arm do
      url "https://github.com/ssgohq/ssgo/releases/download/v#{version}/ss_Darwin_arm64.tar.gz",
        verified: "github.com/ssgohq/ssgo"
      sha256 "a3e3dbafafe7fededa3d7454e0a359cc601d52904aa47747588411506b98c47b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ssgohq/ssgo/releases/download/v#{version}/ss_Linux_x86_64.tar.gz",
        verified: "github.com/ssgohq/ssgo"
      sha256 "99effd354018eee1bd670981a887f6c8ac7c02ba86fb04976dfd887854e96354"
    end
    on_arm do
      url "https://github.com/ssgohq/ssgo/releases/download/v#{version}/ss_Linux_arm64.tar.gz",
        verified: "github.com/ssgohq/ssgo"
      sha256 "327c4b898b1faba6f03a99c3ed5c93dbdfb11083edb25be81157de192ad8f516"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ss"]
    end
  end

  # No zap stanza required
end
