# This file was generated by GoReleaser. DO NOT EDIT.
cask "ss" do
  name "ss"
  desc "All-in-one Go development toolkit with code generation and runtime utilities"
  homepage "https://github.com/ssgohq/ssgo"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ss"

  on_macos do
    on_intel do
      url "https://github.com/ssgohq/ssgo/releases/download/v#{version}/ss_Darwin_x86_64.tar.gz",
        verified: "github.com/ssgohq/ssgo"
      sha256 "a3b5a62ceb4cce28ef7d7ed5840e2bf6403f2c2d25c1e0516fa860a6cbd4af63"
    end
    on_arm do
      url "https://github.com/ssgohq/ssgo/releases/download/v#{version}/ss_Darwin_arm64.tar.gz",
        verified: "github.com/ssgohq/ssgo"
      sha256 "13675a1ab5adbb3080e5118f8635a53ab5b3d0e3a2f4649e1ad52de2a4a8b483"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ssgohq/ssgo/releases/download/v#{version}/ss_Linux_x86_64.tar.gz",
        verified: "github.com/ssgohq/ssgo"
      sha256 "accc6e2fbae5c6e38074567b965a759e74a3ee6efd85b9f553eb005331ba7b84"
    end
    on_arm do
      url "https://github.com/ssgohq/ssgo/releases/download/v#{version}/ss_Linux_arm64.tar.gz",
        verified: "github.com/ssgohq/ssgo"
      sha256 "a60735b424af5424af488c6b01008baddedfd2d7fd611a577265aa2a16e70f4a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ss"]
    end
  end

  # No zap stanza required
end
