# This file was generated by GoReleaser. DO NOT EDIT.
cask "ss" do
  name "ss"
  desc "All-in-one Go development toolkit with code generation and runtime utilities"
  homepage "https://github.com/ssgohq/ssgo"
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ss"

  on_macos do
    on_intel do
      url "https://github.com/ssgohq/ssgo/releases/download/v#{version}/ss_Darwin_x86_64.tar.gz",
        verified: "github.com/ssgohq/ssgo"
      sha256 "c3b7935234e300aa71a7fde303233e98c713e95baa499129735edb12de1895d3"
    end
    on_arm do
      url "https://github.com/ssgohq/ssgo/releases/download/v#{version}/ss_Darwin_arm64.tar.gz",
        verified: "github.com/ssgohq/ssgo"
      sha256 "42dbb0237d4624c803b346c09cc127aa833291d3402bfaccb6b30f649aed3400"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ssgohq/ssgo/releases/download/v#{version}/ss_Linux_x86_64.tar.gz",
        verified: "github.com/ssgohq/ssgo"
      sha256 "83d41c356fe81ffd1f6809f8154298e65d58e3958b1a64247c3b0b234c2130e2"
    end
    on_arm do
      url "https://github.com/ssgohq/ssgo/releases/download/v#{version}/ss_Linux_arm64.tar.gz",
        verified: "github.com/ssgohq/ssgo"
      sha256 "9f2f56778872a9458dd14a236f99bd299d83abe1af64cc1b4c2db0c2661163c1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ss"]
    end
  end

  # No zap stanza required
end
