# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ss < Formula
  desc "Plugin-based CLI tool for development workflows"
  homepage "https://github.com/ssgohq/ss"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ssgohq/ss/releases/download/v0.0.1/ss_Darwin_x86_64.tar.gz"
      sha256 "7d0613a1daa2e2bb890197583ba82d8c5f70da0156c583a962a3d6792259025b"

      def install
        bin.install "ss"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ssgohq/ss/releases/download/v0.0.1/ss_Darwin_arm64.tar.gz"
      sha256 "8c84114fc1eabbdf5e39ea732c000ad007adc4f51f6eab1505e89b13c8b76c7e"

      def install
        bin.install "ss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ssgohq/ss/releases/download/v0.0.1/ss_Linux_x86_64.tar.gz"
      sha256 "53bbcc1b23269551295440a4ba5c386fd38034055c83d3cd1ca91731cb89edab"
      def install
        bin.install "ss"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ssgohq/ss/releases/download/v0.0.1/ss_Linux_arm64.tar.gz"
      sha256 "d1799a03ef4b7defba96d5f59644ad72a7e9816c40e59f3c6e676ebb4de4070b"
      def install
        bin.install "ss"
      end
    end
  end

  test do
    system "#{bin}/ss version"
  end
end
